server:
  port: 8088
spring:
  application:
    name: security_demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/security_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: videon
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
application:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 (you can type `echo 'secret-key'|base64` on your command line)
        base64-secret: NGY5ZjcxY2I2ODAzZDVkMDk5NzNiM2I5MDVmZDdlYWI5ODVhOGY3MzEzNWZhODM5YzRlOWU1MjAzOGMxOWYzZjk1OGMwM2YxNDBjMjU2MGE3YzI0M2QxNWVkY2U2ODU5NDJiZmE5NDg2N2EzZGY3MGRlMTI3ODA0NTk2YjViMTg=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000