server:
  port: 8088
spring:
  application:
    name: security_demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/security_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: videon
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create