spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: videon
    #配置 Jpa
  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: update
#  quartz:
#    auto-startup: true
#    overwrite-existing-jobs: true
#    jdbc:
#      schema: classpath:tables_mysql_innodb.sql
#      initialize-schema: always
#    job-store-type: jdbc
logging:
  level:
    ROOT: INFO
    com.example.quartz: DEBUG
